/**
 * Report Generator — Automated Report Generation
 *
 * Builds a fully formatted plain-text system report from
 * pre-fetched analytics data. No extra dependencies needed.
 *
 * The report includes:
 *  - Summary statistics (tickets, resolution rate, response time)
 *  - Ticket status breakdown
 *  - Priority distribution
 *  - Category distribution
 *  - Crisis ticket summary
 *  - Counselor workload table
 *  - Daily ticket trend (last 14 days)
 *  - Generated timestamp + admin name
 */

/**
 * Draws a simple ASCII bar for distributions.
 * @param {number} count
 * @param {number} total
 * @param {number} width  — max bar width in characters
 */
const asciiBar = (count, total, width = 20) => {
  const filled = total > 0 ? Math.round((count / total) * width) : 0;
  return '█'.repeat(filled) + '░'.repeat(width - filled);
};

/**
 * Right-pads a string to a fixed length for table alignment.
 */
const pad = (str, len) => String(str).padEnd(len, ' ').slice(0, len);

/**
 * Formats a number of hours into a readable string.
 */
const formatHours = (hours) => {
  if (hours === null || hours === undefined) return 'N/A';
  if (hours < 1) return `${Math.round(hours * 60)} min`;
  if (hours < 24) return `${hours}h`;
  return `${(hours / 24).toFixed(1)} days`;
};

/**
 * Main report builder.
 * @param {object} analytics   — data from getAnalytics()
 * @param {string} adminName   — name of the admin generating the report
 * @returns {string}           — full report as plain text
 */
const buildReport = (analytics, adminName = 'Admin') => {
  const now = new Date();
  const lines = [];

  const divider  = '═'.repeat(60);
  const dividerS = '─'.repeat(60);

  // ── Header ──────────────────────────────────────────────────
  lines.push(divider);
  lines.push('       VENTIFY — AUTOMATED SYSTEM REPORT              ');
  lines.push(divider);
  lines.push('');
  lines.push(`  Generated By : ${adminName}`);
  lines.push(`  Generated At : ${now.toLocaleString()}`);
  lines.push(`  Report Period: All time + last 14 days trend`);
  lines.push('');

  // ── 1. Executive Summary ─────────────────────────────────────
  lines.push(divider);
  lines.push('  1. EXECUTIVE SUMMARY');
  lines.push(divider);
  lines.push('');
  lines.push(`  Total Tickets Submitted   : ${analytics.total}`);
  lines.push(`  Resolution Rate           : ${analytics.resolutionRate}%`);
  lines.push(`  Avg First Response Time   : ${formatHours(analytics.avgResponseTimeHours)}`);
  lines.push(`  Avg Resolution Time       : ${formatHours(analytics.avgResolutionTimeHours)}`);
  lines.push(`  Total Crisis Tickets      : ${analytics.totalCrisis || 0}`);
  lines.push(`  Unacknowledged Crisis     : ${analytics.unacknowledgedCrisis || 0}`);
  lines.push('');

  // ── 2. Ticket Status Breakdown ───────────────────────────────
  lines.push(divider);
  lines.push('  2. TICKET STATUS BREAKDOWN');
  lines.push(divider);
  lines.push('');
  lines.push(`  ${pad('Status', 16)} ${pad('Count', 8)} Distribution`);
  lines.push(`  ${dividerS}`);

  const statuses = [
    { label: 'Open',        val: analytics.open },
    { label: 'Assigned',    val: analytics.assigned },
    { label: 'In Progress', val: analytics.inProgress },
    { label: 'Responded',   val: analytics.responded },
    { label: 'Resolved',    val: analytics.resolved },
    { label: 'Closed',      val: analytics.closed },
  ];

  for (const s of statuses) {
    const bar = asciiBar(s.val, analytics.total);
    const pct = analytics.total > 0 ? Math.round((s.val / analytics.total) * 100) : 0;
    lines.push(`  ${pad(s.label, 16)} ${pad(s.val, 8)} ${bar} ${pct}%`);
  }
  lines.push('');

  // ── 3. Priority Distribution ──────────────────────────────────
  lines.push(divider);
  lines.push('  3. PRIORITY DISTRIBUTION');
  lines.push(divider);
  lines.push('');
  lines.push(`  ${pad('Priority', 16)} ${pad('Count', 8)} Distribution`);
  lines.push(`  ${dividerS}`);

  const priorityOrder = ['urgent', 'high', 'medium', 'low'];
  for (const p of priorityOrder) {
    const found = (analytics.byPriority || []).find(x => x._id === p);
    const count = found ? found.count : 0;
    const bar   = asciiBar(count, analytics.total);
    const pct   = analytics.total > 0 ? Math.round((count / analytics.total) * 100) : 0;
    lines.push(`  ${pad(p.toUpperCase(), 16)} ${pad(count, 8)} ${bar} ${pct}%`);
  }
  lines.push('');

  // ── 4. Category Distribution ──────────────────────────────────
  lines.push(divider);
  lines.push('  4. CATEGORY DISTRIBUTION');
  lines.push(divider);
  lines.push('');
  lines.push(`  ${pad('Category', 22)} ${pad('Count', 8)} Distribution`);
  lines.push(`  ${dividerS}`);

  if (!analytics.byCategory || analytics.byCategory.length === 0) {
    lines.push('  No category data available.');
  } else {
    for (const c of analytics.byCategory) {
      const bar = asciiBar(c.count, analytics.total);
      const pct = analytics.total > 0 ? Math.round((c.count / analytics.total) * 100) : 0;
      lines.push(`  ${pad(c.name || 'Uncategorized', 22)} ${pad(c.count, 8)} ${bar} ${pct}%`);
    }
  }
  lines.push('');

  // ── 5. Crisis Ticket Summary ──────────────────────────────────
  lines.push(divider);
  lines.push('  5. CRISIS TICKET SUMMARY');
  lines.push(divider);
  lines.push('');
  lines.push(`  Total Crisis Tickets      : ${analytics.totalCrisis || 0}`);
  lines.push(`  Acknowledged              : ${(analytics.totalCrisis || 0) - (analytics.unacknowledgedCrisis || 0)}`);
  lines.push(`  Unacknowledged            : ${analytics.unacknowledgedCrisis || 0}`);
  const crisisRate = analytics.total > 0
    ? ((analytics.totalCrisis / analytics.total) * 100).toFixed(1)
    : '0.0';
  lines.push(`  Crisis Rate               : ${crisisRate}% of all tickets`);
  lines.push('');
  if ((analytics.unacknowledgedCrisis || 0) > 0) {
    lines.push(`  ⚠ WARNING: ${analytics.unacknowledgedCrisis} crisis ticket(s) have not been acknowledged.`);
    lines.push('    Immediate counselor action is required.');
  } else {
    lines.push('  ✓ All crisis tickets have been acknowledged.');
  }
  lines.push('');

  // ── 6. Counselor Workload ─────────────────────────────────────
  lines.push(divider);
  lines.push('  6. COUNSELOR WORKLOAD');
  lines.push(divider);
  lines.push('');
  lines.push(`  ${pad('Counselor', 22)} ${pad('Active', 8)} ${pad('Status', 14)} Load`);
  lines.push(`  ${dividerS}`);

  if (!analytics.counselorWorkload || analytics.counselorWorkload.length === 0) {
    lines.push('  No counselors registered.');
  } else {
    const maxLoad = analytics.counselorWorkload[0]?.activeCount || 1;
    for (const c of analytics.counselorWorkload) {
      const bar    = asciiBar(c.activeCount, maxLoad, 12);
      const status = c.availability ? 'Available' : 'Unavailable';
      lines.push(`  ${pad(c.name, 22)} ${pad(c.activeCount, 8)} ${pad(status, 14)} ${bar}`);
    }
  }
  lines.push('');

  // ── 7. Daily Ticket Trend ─────────────────────────────────────
  lines.push(divider);
  lines.push('  7. DAILY TICKET TREND — LAST 14 DAYS');
  lines.push(divider);
  lines.push('');

  if (!analytics.dailyTrend || analytics.dailyTrend.length === 0) {
    lines.push('  No ticket activity in the last 14 days.');
  } else {
    const maxCount = Math.max(...analytics.dailyTrend.map(d => d.count), 1);
    for (const d of analytics.dailyTrend) {
      const bar = asciiBar(d.count, maxCount, 24);
      lines.push(`  ${pad(d.date, 14)} ${bar} ${d.count}`);
    }
  }
  lines.push('');

  // ── Footer ───────────────────────────────────────────────────
  lines.push(divider);
  lines.push('  END OF REPORT — VENTIFY Student Mental Health Portal ');
  lines.push(`  Confidential — For authorised personnel only         `);
  lines.push(divider);

  return lines.join('\n');
};

module.exports = { buildReport };